export const GET_BUCKETS = 'GET_BUCKETS';
export const CREATE_BUCKET = 'CREATE_BUCKET';
export const DELETE_BUCKET = 'DELETE_BUCKET';

export const SET_NAME_ALREADY_EXIST_EXCEPTION = 'SET_NAME_ALREADY_EXIST_EXCEPTION';
export const UNSET_NAME_ALREADY_EXIST_EXCEPTION = 'UNSET_NAME_ALREADY_EXIST_EXCEPTION';

export const SELECT_BUCKET = 'SELECT_BUCKET';
export const DESELECT_BUCKET = 'DESELECT_BUCKET';

