export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';
export const PUSH_LOADING = 'PUSH_LOADING';
export const POP_LOADING = 'POP_LOADING';
export const SET_IS_CONNECTED = 'SET_IS_CONNECTED';

export const SET_SORTING = 'SET_SORTING';

export const SHOW_ACTION_BAR = 'SHOW_ACTION_BAR';
export const HIDE_ACTION_BAR = 'HIDE_ACTION_BAR';
export const SINGLE_ITEM_ACTIONS_SELECTED = 'SINGLE_ITEM_ACTIONS_SELECTED';
export const SET_SELECTION_ID = 'SET_SELECTION_ID';
export const DISABLE_SELECTION_MODE = 'DISABLE_SELECTION_MODE';

export const SHOW_CREATE_BUCKET_INPUT = 'SHOW_CREATE_BUCKET_INPUT';
export const HIDE_CREATE_BUCKET_INPUT = 'HIDE_CREATE_BUCKET_INPUT';




